# Site settings
title: "Tunaxor's Dev Blog"
email: scythes.lol@gmail.com
description: This is meant to be my Resume and Dev Experiences blog site

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://angelmunoz.github.io"
twitter_username: Daniel_Tuna
github_username:  AngelMunoz

# Build settings
markdown: kramdown
